SOLVER:
  IMS_PER_BATCH: 2
  BATCH_ACCUMULATION: 0
  BASE_LR: 1e-4
  STEPS: (25,)
  WEIGHT_DECAY: 0.0001
  OPTIMIZER: "ADAM"
  AMSGRAD: True
  PATIENCE: 2
  PATIENCE_MIN_DELTA: 0

DATALOADER:
  NUM_WORKERS: 8

DATASETS:
  DATA_DIR: '/home/griftj/phd/data/cad_aerial_8_sub_test'
  SELECT_VISIBLE: False
  BUFFER: .4
  BINARY_TRESHOLD: .5
  INCLUDE_URBAN: False
  PATCHES_DIR: 'patches_25'
  DOWNSAMPLE_FACTOR: 1.
  TRAIN_SAMPLE: True
  TRAIN_SAMPLE_RATE: .25
  TEST_SAMPLE: False
  TEST_SAMPLE_RATE: 1.
  PRED_DIR: 'preds'
  RESOLUTIONS: [512, 256, 128, 64, 32]
  IMG_SIZE: 512
  SPLIT: False
  CREATE_PATCHES: False
  REFERENCE_TYPE: 'final'

MODEL:
  RUN_TYPE: "predict"
  PACKAGE: "models.cadnet.cadnet"
  CLASS_NAME: "CadNET"
  BACKBONE: "resunet_multi_coa"
  DEVICE: "cuda:1"
  USE_PRETRAINED: False
  TRAINED_MODEL: 'model_00006.pth'
  USE_MULTI: True
  USE_COA: True
  USE_TOPO: False
  USE_BRK: True

  WRITE_PATCH_PREDS: False
  WRITE_MOSAIC_RASTER: False
  WRITE_RASTER_STATS: False
  WRITE_EVALUATE_POLIS: True

  TEST_OVERLAP_50: True
  WRITE_PATCH_PREDS_SAMPLE_RATE: 50
  MOSAIC_TILE: ['tile-120000-430000', 'tile-200000-540000']
  TYPE_POLY_PRED: 'concat'
  SNIP_PREDS: 10.
  CONCAT_ANGLE: .025

POLY:
  TOLERANCE: 10.