from yacs.config import CfgNode as CN

cfg = CN()

cfg.DATASETS = CN()
cfg.DATASETS.SPLIT = False
cfg.DATASETS.CREATE_PATCHES = False

cfg.DATASETS.DATA_DIR = '/data/cad_aerial_8/'
cfg.DATASETS.SELECT_VISIBLE = False
cfg.DATASETS.BUFFER = .5
cfg.DATASETS.BINARY_TRESHOLD = .5
cfg.DATASETS.INCLUDE_URBAN = True

cfg.DATASETS.IMAGES_DIR = 'images'    
cfg.DATASETS.REF_DIR = 'reference'
cfg.DATASETS.URBAN_FILE = '/brt_bebouwde_kom.gpkg'
cfg.DATASETS.PRED_DIR = 'preds'
cfg.DATASETS.MOSAIC_DIR = 'mosaic_preds'
cfg.DATASETS.PATCHES_DIR = 'patches'
cfg.DATASETS.DOWNSAMPLE_FACTOR = 0.5
cfg.DATASETS.RESOLUTIONS = [512]
cfg.DATASETS.IMG_SIZE = 512
cfg.DATASETS.TRAIN_SAMPLE = False
cfg.DATASETS.TRAIN_SAMPLE_RATE = 1.
cfg.DATASETS.TEST_SAMPLE = False
cfg.DATASETS.TEST_SAMPLE_RATE = 1.
cfg.DATASETS.REFERENCE_TYPE = 'brk'

cfg.SOLVER = CN()
cfg.SOLVER.IMS_PER_BATCH = 6
cfg.SOLVER.BATCH_ACCUMULATION = 0
cfg.SOLVER.MAX_EPOCH = 30
cfg.SOLVER.OPTIMIZER = "ADAM"
cfg.SOLVER.BASE_LR = 0.01
cfg.SOLVER.BACKBONE_LR_FACTOR=1.0
cfg.SOLVER.BIAS_LR_FACTOR = 1
cfg.SOLVER.MOMENTUM = 0.9
cfg.SOLVER.WEIGHT_DECAY = 0.0002
cfg.SOLVER.WEIGHT_DECAY_BIAS = 0
cfg.SOLVER.GAMMA = 0.1
cfg.SOLVER.STEPS = (25,)
cfg.SOLVER.CHECKPOINT_PERIOD = 1
cfg.SOLVER.AMSGRAD = False
cfg.SOLVER.STATIC_STEP = 25
cfg.SOLVER.PATIENCE = 3
cfg.SOLVER.PATIENCE_MIN_DELTA = 0

cfg.DATALOADER = CN()
cfg.DATALOADER.NUM_WORKERS = 8

cfg.MODEL = CN()
cfg.MODEL.PACKAGE = 'models.cadnet.cadnet'
cfg.MODEL.CLASS_NAME = ''
cfg.MODEL.BACKBONE = ''
cfg.MODEL.USE_DISTANCE = False
cfg.MODEL.USE_MULTI = False
cfg.MODEL.USE_COA = False
cfg.MODEL.USE_TOPO = False
cfg.MODEL.USE_BRK = False
cfg.MODEL.POLYGONIZE = False

cfg.MODEL.WRITE_PATCH_PREDS = False
cfg.MODEL.WRITE_MOSAIC_RASTER = False
cfg.MODEL.WRITE_RASTER_STATS = False
cfg.MODEL.WRITE_EVALUATE_POLIS = False

cfg.MODEL.TEST_OVERLAP_50 = False
cfg.MODEL.WRITE_PATCH_PREDS_SAMPLE_RATE = 10
cfg.MODEL.MOSAIC_TILE = ['tile-120000-430000', 'tile-200000-540000']
cfg.MODEL.SNIP_PREDS = 0.
cfg.MODEL.CONCAT_ANGLE = .025
cfg.MODEL.TYPE_POLY_PRED = ''

cfg.MODEL.USE_PRETRAINED = False
cfg.MODEL.TRAINED_MODEL = 'model_00000.pth'
cfg.MODEL.DEVICE = "cuda:0"
cfg.MODEL.RUN_TYPES = ['train', 'predict']
cfg.MODEL.RUN_TYPE = ''

cfg.WEIGHTS = CN()

cfg.WEIGHTS.SEG_LOSS_512_CAD = 16.
cfg.WEIGHTS.SEG_LOSS_S512_CAD  = 8.
cfg.WEIGHTS.SEG_LOSS_S256_CAD  = 4.
cfg.WEIGHTS.SEG_LOSS_S128_CAD  = 2.
cfg.WEIGHTS.SEG_LOSS_S64_CAD  = 1
cfg.WEIGHTS.SEG_LOSS_S32_CAD  = .5

cfg.WEIGHTS.SEG_COA_LOSS_512_CAD  = 8.
cfg.WEIGHTS.SEG_COA_LOSS_S512_CAD  = 4.
cfg.WEIGHTS.SEG_COA_LOSS_S256_CAD  = 2.
cfg.WEIGHTS.SEG_COA_LOSS_S128_CAD  = 1
cfg.WEIGHTS.SEG_COA_LOSS_S64_CAD  = .5
cfg.WEIGHTS.SEG_COA_LOSS_S32_CAD  = .25

cfg.WEIGHTS.SEG_LOSS_512_CAD_VIS = 16.
cfg.WEIGHTS.SEG_LOSS_S512_CAD_VIS  = 8.
cfg.WEIGHTS.SEG_LOSS_S256_CAD_VIS  = 4.
cfg.WEIGHTS.SEG_LOSS_S128_CAD_VIS  = 2.
cfg.WEIGHTS.SEG_LOSS_S64_CAD_VIS  = 1
cfg.WEIGHTS.SEG_LOSS_S32_CAD_VIS  = .5

cfg.WEIGHTS.SEG_COA_LOSS_512_CAD_VIS  = 8.
cfg.WEIGHTS.SEG_COA_LOSS_S512_CAD_VIS  = 4.
cfg.WEIGHTS.SEG_COA_LOSS_S256_CAD_VIS  = 2.
cfg.WEIGHTS.SEG_COA_LOSS_S128_CAD_VIS  = 1
cfg.WEIGHTS.SEG_COA_LOSS_S64_CAD_VIS  = .5
cfg.WEIGHTS.SEG_COA_LOSS_S32_CAD_VIS  = .25

cfg.WEIGHTS.SEG_LOSS_512_CAD_INV = 4.
cfg.WEIGHTS.SEG_LOSS_S512_CAD_INV = 2.
cfg.WEIGHTS.SEG_LOSS_S256_CAD_INV = 1.
cfg.WEIGHTS.SEG_LOSS_S128_CAD_INV = .5
cfg.WEIGHTS.SEG_LOSS_S64_CAD_INV = .25
cfg.WEIGHTS.SEG_LOSS_S32_CAD_INV = .0625

cfg.WEIGHTS.SEG_COA_LOSS_512_CAD_INV = 2.
cfg.WEIGHTS.SEG_COA_LOSS_S512_CAD_INV = 1.
cfg.WEIGHTS.SEG_COA_LOSS_S256_CAD_INV = .5
cfg.WEIGHTS.SEG_COA_LOSS_S128_CAD_INV = 25
cfg.WEIGHTS.SEG_COA_LOSS_S64_CAD_INV = .0625
cfg.WEIGHTS.SEG_COA_LOSS_S32_CAD_INV = .015625

cfg.WEIGHTS.COA_D1_LOSS = .6
cfg.WEIGHTS.COA_D3_LOSS = .4

cfg.WEIGHTS.SEG_LOSS_512_TOPO = 8.
cfg.WEIGHTS.SEG_LOSS_S512_TOPO = 4.
cfg.WEIGHTS.SEG_LOSS_S256_TOPO = 2.
cfg.WEIGHTS.SEG_LOSS_S128_TOPO = 1.
cfg.WEIGHTS.SEG_LOSS_S64_TOPO = .5
cfg.WEIGHTS.SEG_LOSS_S32_TOPO = .25

cfg.WEIGHTS.SEG_COA_LOSS_512_TOPO = 4.
cfg.WEIGHTS.SEG_COA_LOSS_S512_TOPO = 2.
cfg.WEIGHTS.SEG_COA_LOSS_S256_TOPO = 1.
cfg.WEIGHTS.SEG_COA_LOSS_S128_TOPO = .5
cfg.WEIGHTS.SEG_COA_LOSS_S64_TOPO = .25
cfg.WEIGHTS.SEG_COA_LOSS_S32_TOPO = .125

cfg.POLY = CN()
cfg.POLY.INIT_METHOD = "skeleton"
cfg.POLY.TOLERANCE = 5.

cfg.OUTPUT_DIR = "./output"
cfg.INPUT_DIR = "./output"